name: markscribe

on:
  push:
  workflow_dispatch:
  # Schedule updates (every 6 hours)
  schedule: [{cron: "0 */1 * * *"}]

jobs:
  markscribe:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Generate README
        uses: muesli/readme-scribe@master
        env:
          GITHUB_TOKEN: ${{  secrets.METRICS_TOKEN  }}
        with:
          template: "README.tpl"
          writeTo: "README.md"

      - uses: stefanzweifel/git-auto-commit-action@v5
        env:
          GITHUB_TOKEN: ${{  secrets.METRICS_TOKEN  }}
        with:
          commit_message: Update generated README
          commit_user_name: readme-scribe 🤖
          commit_user_email: actions@github.com
          commit_author: readme-scribe 🤖 <actions@github.com>
